# Generated by Django 6.0.3 on 2026-04-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Primary account', max_length=120)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(max_length=64)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='Optional UPI VPA for QR / apps', max_length=120)),
                ('instructions', models.TextField(blank=True, help_text='Shown on checkout (e.g. use order id as payment note).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_reference',
            field=models.CharField(blank=True, help_text='UTR / transaction id submitted by customer', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('bank_transfer', 'Bank transfer')], default='razorpay', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending_verification', 'Pending verification'), ('success', 'Success'), ('failed', 'Failed')], default='created', max_length=32),
        ),
    ]
