# Generated by Django 6.0.4 on 2026-04-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
    ]
