# Generated by Django 6.0.4 on 2026-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Managment', '0002_appointment_reminder_sent_doctor_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
